In [3]:
import numpy as np

In [2]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [6]:
# Show the numpy array dimensions

A.ndim

2

In [5]:
# Show the numpy array shape

A.shape

(3, 3)

In [7]:
# Show the numpy array size

A.size

9

In [10]:
# Access the element on the second row and third column

A[1, 2]

np.int64(23)

In [11]:
# Access the element on the first row and first column

A[0][0]

np.int64(11)

In [12]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

In [13]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

In [14]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [15]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [16]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [17]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [18]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [23]:
Y = np.array([[2, 1], [1, 2]]) 
Y


array([[2, 1],
       [1, 2]])

In [24]:
X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [25]:

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [27]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [28]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [29]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [30]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [31]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [32]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

In [34]:
c = np.array([100,1,2,3,0])
c

array([100,   1,   2,   3,   0])

In [36]:
a=np.array([0,1]) 

b=np.array([1,0]) 

np.dot(a,b) 

np.int64(0)

In [39]:
X=np.array([[1,0],[0,1]]) 

Y=np.array([[0,1],[1,0]]) 

Z=X+Y 
Z

array([[1, 1],
       [1, 1]])

In [42]:
X=np.array([[1,0,1],[2,2,2]]) 

out=X[0:2,2]
out

array([1, 2])

In [44]:
X=np.array([[1,0],[0,1]]) 

Y=np.array([[2,1],[1,2]]) 

Z=np.dot(X,Y) 
Z

array([[2, 1],
       [1, 2]])

In [4]:
a=np.array([0,1,0,1,0]) 

b=np.array([1,0,1,0,1]) 

a+b 

array([1, 1, 1, 1, 1])

In [5]:
a=np.array([1,1,1,1,1]) 

a+10

array([11, 11, 11, 11, 11])